name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - pandas=2.1.3
  - scikit-learn=1.3.2
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - category_encoders==2.6.3
